apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: airflow-webserver
  name: airflow-webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: airflow-webserver
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/: "true"
        io.kompose.service: airflow-webserver
    spec:
      containers:
        - args:
            - webserver
          image: airflow-webserver
          livenessProbe:
            exec:
              command:
                - curl
                - --fail
                - http://localhost:8080/health
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 10
          name: airflow-webserver
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
