apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: ubuntu
  name: ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ubuntu
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/default: "true"
        io.kompose.service: ubuntu
    spec:
      containers:
        - env:
            - name: TZ
              value: Europe/Moscow
          image: ubuntu:20.04
          name: modelserver
          ports:
            - containerPort: 9100
            - containerPort: 5000
          resources: {}
          tty: true
          volumeMounts:
            - mountPath: /root/server
              name: ubuntu-claim0
      hostname: modelserver
      restartPolicy: Always
      volumes:
        - name: ubuntu-claim0
          persistentVolumeClaim:
            claimName: ubuntu-claim0
status: {}
