apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: airflow-scheduler
  name: airflow-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: airflow-scheduler
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/: "true"
        io.kompose.service: airflow-scheduler
    spec:
      containers:
        - args:
            - scheduler
          image: airflow-scheduler
          livenessProbe:
            exec:
              command:
                - airflow jobs check --job-type SchedulerJob --hostname "${HOSTNAME}"
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 10
          name: airflow-scheduler
          resources: {}
      restartPolicy: Always
status: {}
